import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1772145877171 implements MigrationInterface {
    name = 'Migration1772145877171'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "listing_revisions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "listingId" uuid NOT NULL, "version" integer NOT NULL, "statusBefore" character varying(20), "statusAfter" character varying(20) NOT NULL, "snapshot" jsonb NOT NULL, "changeReason" text, "changedBy" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_revision_version" UNIQUE ("listingId", "version"), CONSTRAINT "PK_4934af086178e29bb8b46c8c893" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c134b2b0165e2bf9e479e5bb03" ON "listing_revisions" ("listingId") `);
        await queryRunner.query(`CREATE TABLE "image_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "listing_id" uuid, "job_id" uuid, "s3_bucket" character varying(100) NOT NULL, "s3_key" character varying(500) NOT NULL, "s3_key_thumb" character varying(500), "cdn_url" text, "original_filename" text, "mime_type" character varying(50) NOT NULL, "file_size_bytes" bigint NOT NULL, "width" integer, "height" integer, "blurhash" character varying(50), "sort_order" integer NOT NULL DEFAULT '0', "is_primary" boolean NOT NULL DEFAULT false, "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_68a641039393a26cc181632b040" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_image_job" ON "image_assets" ("job_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_image_s3" ON "image_assets" ("s3_bucket", "s3_key") `);
        await queryRunner.query(`CREATE INDEX "idx_image_listing" ON "image_assets" ("listing_id") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE TABLE "channel_connections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "channel" character varying(30) NOT NULL, "user_id" uuid NOT NULL, "account_name" character varying(200), "external_account_id" character varying(200), "encrypted_tokens" text NOT NULL, "token_expires_at" TIMESTAMP WITH TIME ZONE, "scope" character varying(500), "status" character varying(20) NOT NULL DEFAULT 'active', "last_sync_at" TIMESTAMP WITH TIME ZONE, "last_error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2ae1fe901084592fd4d6795faea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_channel_conn_user" ON "channel_connections" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "channel" character varying(30) NOT NULL, "connection_id" uuid, "external_order_id" character varying(100), "external_url" text, "status" character varying(30) NOT NULL DEFAULT 'pending', "buyer_username" character varying(200), "buyer_email" character varying(200), "buyer_name" character varying(200), "shipping_name" character varying(200), "shipping_address_1" text, "shipping_address_2" text, "shipping_city" character varying(100), "shipping_state" character varying(100), "shipping_zip" character varying(20), "shipping_country" character(2), "shipping_method" character varying(100), "tracking_number" character varying(100), "tracking_carrier" character varying(50), "shipped_at" TIMESTAMP WITH TIME ZONE, "delivered_at" TIMESTAMP WITH TIME ZONE, "subtotal" numeric(10,2) NOT NULL DEFAULT '0', "shipping_cost" numeric(10,2) NOT NULL DEFAULT '0', "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "total_amount" numeric(10,2) NOT NULL DEFAULT '0', "currency" character(3) NOT NULL DEFAULT 'USD', "marketplace_fee" numeric(10,2) NOT NULL DEFAULT '0', "net_revenue" numeric(10,2), "refund_amount" numeric(10,2) NOT NULL DEFAULT '0', "refund_reason" text, "refunded_at" TIMESTAMP WITH TIME ZONE, "ordered_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "paid_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_order_external" ON "orders" ("channel", "external_order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_order_buyer" ON "orders" ("buyer_email") `);
        await queryRunner.query(`CREATE INDEX "idx_order_date" ON "orders" ("ordered_at") `);
        await queryRunner.query(`CREATE INDEX "idx_order_channel" ON "orders" ("channel", "ordered_at") `);
        await queryRunner.query(`CREATE INDEX "idx_order_status" ON "orders" ("status") `);
        await queryRunner.query(`CREATE TABLE "tenant_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category" character varying(50) NOT NULL, "key" character varying(100) NOT NULL, "value" jsonb NOT NULL, "description" text, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedBy" uuid, CONSTRAINT "uq_setting_category_key" UNIQUE ("category", "key"), CONSTRAINT "PK_69225c0ca64bcbbf9af8a217043" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipping_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "carrier" character varying(50) NOT NULL, "service" character varying(100) NOT NULL, "handlingTime" integer NOT NULL DEFAULT '1', "costType" character varying(20) NOT NULL, "flatCost" numeric(8,2), "weightBased" boolean NOT NULL DEFAULT false, "domesticOnly" boolean NOT NULL DEFAULT true, "isDefault" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ff6dbc0cbb1403e01f92a6ee3a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pricing_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "ruleType" character varying(30) NOT NULL, "channel" character varying(30), "categoryId" character varying(20), "brand" character varying(100), "parameters" jsonb NOT NULL, "priority" integer NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fda27bb8db4630894decda61ff6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "listing_id" uuid, "external_item_id" character varying(100), "sku" character varying(100), "title" text NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unit_price" numeric(10,2) NOT NULL, "total_price" numeric(10,2) NOT NULL, "fulfilled" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_order_item_listing" ON "order_items" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "idx_order_item_order" ON "order_items" ("order_id") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipientId" uuid, "type" character varying(50) NOT NULL, "title" character varying(200) NOT NULL, "body" text, "icon" character varying(30), "severity" character varying(10) NOT NULL DEFAULT 'info', "entityType" character varying(50), "entityId" uuid, "actionUrl" text, "read" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP WITH TIME ZONE, "dismissed" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_notif_recipient" ON "notifications" ("recipientId") `);
        await queryRunner.query(`CREATE INDEX "idx_notif_type" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE TABLE "inventory_ledger" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "listing_id" uuid NOT NULL, "quantity_total" integer NOT NULL DEFAULT '0', "quantity_reserved" integer NOT NULL DEFAULT '0', "quantity_available" integer, "quantity_listed_ebay" integer NOT NULL DEFAULT '0', "quantity_listed_shopify" integer NOT NULL DEFAULT '0', "low_stock_threshold" integer NOT NULL DEFAULT '2', "reorder_point" integer NOT NULL DEFAULT '0', "version" integer NOT NULL, "last_reconciled_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e80d1aa0ddd69622c182116f5cf" UNIQUE ("listing_id"), CONSTRAINT "REL_e80d1aa0ddd69622c182116f5c" UNIQUE ("listing_id"), CONSTRAINT "PK_56ba7cef08f3263f90418ddfeef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ledger_low_stock" ON "inventory_ledger" ("quantity_total") WHERE "quantity_total" - "quantity_reserved" <= "low_stock_threshold"`);
        await queryRunner.query(`CREATE TABLE "inventory_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "listing_id" uuid NOT NULL, "event_type" character varying(30) NOT NULL, "quantity_change" integer NOT NULL, "quantity_before" integer NOT NULL, "quantity_after" integer NOT NULL, "source_channel" character varying(30), "source_order_id" character varying(100), "source_reference" text, "idempotency_key" character varying(200), "reason" text, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_0eccd00df2f17d4a36a2bb2e507" UNIQUE ("idempotency_key"), CONSTRAINT "PK_2e23c05381d151be5dad80bbe10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_event_source" ON "inventory_events" ("source_channel", "source_order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_event_type" ON "inventory_events" ("event_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_event_listing" ON "inventory_events" ("listing_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "ingestion_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" character varying(20) NOT NULL DEFAULT 'pending', "mode" character varying(20) NOT NULL, "source_type" character varying(20) NOT NULL DEFAULT 'upload', "image_count" integer NOT NULL DEFAULT '0', "ai_provider" character varying(30), "ai_model" character varying(50), "ai_started_at" TIMESTAMP WITH TIME ZONE, "ai_completed_at" TIMESTAMP WITH TIME ZONE, "ai_cost_usd" numeric(8,4), "review_status" character varying(20) NOT NULL DEFAULT 'pending', "reviewed_by" uuid, "reviewed_at" TIMESTAMP WITH TIME ZONE, "review_notes" text, "listing_id" uuid, "attempt_count" integer NOT NULL DEFAULT '0', "max_attempts" integer NOT NULL DEFAULT '3', "last_error" text, "next_retry_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_78a3cba789582043cfc8ba82edd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_job_review" ON "ingestion_jobs" ("review_status") WHERE "review_status" = 'needs_review'`);
        await queryRunner.query(`CREATE INDEX "idx_job_status" ON "ingestion_jobs" ("status") `);
        await queryRunner.query(`CREATE TABLE "ai_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "raw_response" jsonb NOT NULL, "provider" character varying(30) NOT NULL, "model" character varying(50) NOT NULL, "tokens_used" integer, "latency_ms" integer, "extracted_title" text, "extracted_brand" text, "extracted_mpn" text, "extracted_oem_number" text, "extracted_part_type" text, "extracted_condition" text, "extracted_price_estimate" numeric(10,2), "extracted_description" text, "extracted_features" text array, "extracted_fitment_raw" jsonb, "confidence_title" real, "confidence_brand" real, "confidence_mpn" real, "confidence_part_type" real, "confidence_overall" real NOT NULL, "matched_existing_id" uuid, "match_confidence" real, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c65603014e94bf65ea60ce5a721" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ai_result_confidence" ON "ai_results" ("confidence_overall") `);
        await queryRunner.query(`CREATE INDEX "idx_ai_result_job" ON "ai_results" ("job_id") `);
        await queryRunner.query(`CREATE TABLE "fitment_makes" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "aces_id" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b3b847ac873db83081267b9943" UNIQUE ("aces_id"), CONSTRAINT "UQ_9a2d705447a819b8e30e77365bf" UNIQUE ("slug"), CONSTRAINT "PK_b9799dd6ac31b0f4cecae8e6690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a2d705447a819b8e30e77365b" ON "fitment_makes" ("slug") `);
        await queryRunner.query(`CREATE TABLE "fitment_models" ("id" SERIAL NOT NULL, "make_id" integer NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "aces_id" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_004c9f763e8b66ac7d9096b46d8" UNIQUE ("aces_id"), CONSTRAINT "UQ_0745c4b3c088ceffc046c3f87e8" UNIQUE ("make_id", "slug"), CONSTRAINT "PK_78ff81a168b5a120bcc3ca8eea3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32713bba8792485c0a4cc47cf6" ON "fitment_models" ("make_id") `);
        await queryRunner.query(`CREATE TABLE "fitment_submodels" ("id" SERIAL NOT NULL, "model_id" integer NOT NULL, "name" character varying(100) NOT NULL, "aces_id" integer, CONSTRAINT "UQ_efbacdbac0f64360aa8ae0cdc0a" UNIQUE ("aces_id"), CONSTRAINT "UQ_03810ffedf104a8fdabaf45ef91" UNIQUE ("model_id", "name"), CONSTRAINT "PK_a4dd840cacb5b543d6713459df4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fitment_engines" ("id" SERIAL NOT NULL, "code" character varying(50) NOT NULL, "displacement_l" numeric(4,1), "cylinders" smallint, "fuel_type" character varying(30), "aspiration" character varying(30), "aces_id" integer, CONSTRAINT "UQ_730f9e588bb02ca24fac578d926" UNIQUE ("aces_id"), CONSTRAINT "UQ_0c4bddec37ab15a8a3fac4b7e52" UNIQUE ("code"), CONSTRAINT "PK_cfefb79a9e152d75b5db7584db3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "part_fitments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "listing_id" uuid NOT NULL, "make_id" integer NOT NULL, "model_id" integer NOT NULL, "submodel_id" integer, "year_start" smallint NOT NULL, "year_end" smallint NOT NULL, "engine_id" integer, "source" character varying(20) NOT NULL DEFAULT 'manual', "confidence" real, "verified" boolean NOT NULL DEFAULT false, "verified_by" uuid, "verified_at" TIMESTAMP WITH TIME ZONE, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f6d40618d1ea8773c70357c7408" UNIQUE ("listing_id", "make_id", "model_id", "year_start", "year_end", "engine_id"), CONSTRAINT "PK_fc80d6cb9534c2a2a74cecec400" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_fitment_vehicle" ON "part_fitments" ("make_id", "model_id", "year_start", "year_end") `);
        await queryRunner.query(`CREATE INDEX "idx_fitment_listing" ON "part_fitments" ("listing_id") `);
        await queryRunner.query(`CREATE TABLE "fitment_years" ("id" SERIAL NOT NULL, "year" smallint NOT NULL, CONSTRAINT "UQ_121920446573219f54cd8ce0bc8" UNIQUE ("year"), CONSTRAINT "PK_14cc37c98b9e39f1d341a3097c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid, "listingId" uuid NOT NULL, "channel" character varying(30) NOT NULL, "quantitySold" integer NOT NULL DEFAULT '1', "salePrice" numeric(10,2) NOT NULL, "currency" character(3) NOT NULL DEFAULT 'USD', "marketplaceFee" numeric(10,2), "netRevenue" numeric(10,2), "soldAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0004c37d7d3cfc1064f9d797b67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sales_listing" ON "sales_records" ("listingId") `);
        await queryRunner.query(`CREATE INDEX "idx_sales_channel" ON "sales_records" ("channel") `);
        await queryRunner.query(`CREATE INDEX "idx_sales_date" ON "sales_records" ("soldAt") `);
        await queryRunner.query(`CREATE TABLE "channel_webhook_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "channel" character varying(30) NOT NULL, "event_type" character varying(100) NOT NULL, "external_id" character varying(200), "payload" jsonb NOT NULL DEFAULT '{}', "processing_status" character varying(20) NOT NULL DEFAULT 'received', "processing_error" text, "processed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b0f0628f389e98019a22aba4a04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_webhook_log_channel" ON "channel_webhook_logs" ("channel") `);
        await queryRunner.query(`CREATE TABLE "channel_listings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "connection_id" uuid NOT NULL, "listing_id" uuid NOT NULL, "external_id" character varying(200) NOT NULL, "external_url" character varying(500), "sync_status" character varying(20) NOT NULL DEFAULT 'synced', "last_pushed_version" integer NOT NULL DEFAULT '0', "last_synced_at" TIMESTAMP WITH TIME ZONE, "last_error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_55b81574b7bd0381d59a4eba2b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_channel_listing_external" ON "channel_listings" ("connection_id", "external_id") `);
        await queryRunner.query(`CREATE INDEX "idx_channel_listing_listing" ON "channel_listings" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "idx_channel_listing_conn" ON "channel_listings" ("connection_id") `);
        await queryRunner.query(`CREATE TABLE "dashboard_metrics_cache" ("metricKey" character varying(100) NOT NULL, "metricValue" jsonb NOT NULL, "computedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0e2c513ccad368f20c56bcfb884" PRIMARY KEY ("metricKey"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entityType" character varying(50) NOT NULL, "entityId" uuid NOT NULL, "action" character varying(30) NOT NULL, "actorId" uuid, "actorType" character varying(20) NOT NULL DEFAULT 'user', "changes" jsonb, "metadata" jsonb NOT NULL DEFAULT '{}', "ipAddress" inet, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_entity" ON "audit_logs" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_action" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_actor" ON "audit_logs" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_created" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(200) NOT NULL, "passwordHash" text NOT NULL, "name" character varying(200), "role" character varying(20) NOT NULL DEFAULT 'user', "active" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "listing_records" ADD "status" character varying(20) NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "listing_records" ADD "version" integer NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE "listing_records" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "listing_records" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "listing_records" ADD "updatedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "listing_records" ADD "publishedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "listing_records" ADD "ebayListingId" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "listing_records" ADD "shopifyProductId" character varying(64)`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_channel"`);
        await queryRunner.query(`CREATE INDEX "idx_order_channel" ON "orders" ("channel", "ordered_at") `);
        await queryRunner.query(`ALTER TABLE "image_assets" ADD CONSTRAINT "FK_ebae1924f6d1fd22aa4c8bc12fd" FOREIGN KEY ("listing_id") REFERENCES "listing_records"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a837fef7baa06a7d7d1b175a1f8" FOREIGN KEY ("connection_id") REFERENCES "channel_connections"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_ledger" ADD CONSTRAINT "FK_e80d1aa0ddd69622c182116f5cf" FOREIGN KEY ("listing_id") REFERENCES "listing_records"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingestion_jobs" ADD CONSTRAINT "FK_ba1faf3bce0450f77f5fe1fbfa7" FOREIGN KEY ("listing_id") REFERENCES "listing_records"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_results" ADD CONSTRAINT "FK_566b2de994f05c69ae470d9daf9" FOREIGN KEY ("job_id") REFERENCES "ingestion_jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fitment_models" ADD CONSTRAINT "FK_32713bba8792485c0a4cc47cf66" FOREIGN KEY ("make_id") REFERENCES "fitment_makes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fitment_submodels" ADD CONSTRAINT "FK_2a3fc1955f16c3983aff448bbb4" FOREIGN KEY ("model_id") REFERENCES "fitment_models"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part_fitments" ADD CONSTRAINT "FK_ba5558dbcdc334ff010732d4bf0" FOREIGN KEY ("listing_id") REFERENCES "listing_records"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part_fitments" ADD CONSTRAINT "FK_69abb32df15df40ca5974ed48f9" FOREIGN KEY ("make_id") REFERENCES "fitment_makes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part_fitments" ADD CONSTRAINT "FK_fdb70f7be020822cc7faa4c904b" FOREIGN KEY ("model_id") REFERENCES "fitment_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part_fitments" ADD CONSTRAINT "FK_72e494eb4d595e7a7cea1eedaf0" FOREIGN KEY ("submodel_id") REFERENCES "fitment_submodels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "part_fitments" ADD CONSTRAINT "FK_1a2048680da1213856a8a46510b" FOREIGN KEY ("engine_id") REFERENCES "fitment_engines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_listings" ADD CONSTRAINT "FK_f8a4918e794208c5d7ae082355a" FOREIGN KEY ("connection_id") REFERENCES "channel_connections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "channel_listings" DROP CONSTRAINT "FK_f8a4918e794208c5d7ae082355a"`);
        await queryRunner.query(`ALTER TABLE "part_fitments" DROP CONSTRAINT "FK_1a2048680da1213856a8a46510b"`);
        await queryRunner.query(`ALTER TABLE "part_fitments" DROP CONSTRAINT "FK_72e494eb4d595e7a7cea1eedaf0"`);
        await queryRunner.query(`ALTER TABLE "part_fitments" DROP CONSTRAINT "FK_fdb70f7be020822cc7faa4c904b"`);
        await queryRunner.query(`ALTER TABLE "part_fitments" DROP CONSTRAINT "FK_69abb32df15df40ca5974ed48f9"`);
        await queryRunner.query(`ALTER TABLE "part_fitments" DROP CONSTRAINT "FK_ba5558dbcdc334ff010732d4bf0"`);
        await queryRunner.query(`ALTER TABLE "fitment_submodels" DROP CONSTRAINT "FK_2a3fc1955f16c3983aff448bbb4"`);
        await queryRunner.query(`ALTER TABLE "fitment_models" DROP CONSTRAINT "FK_32713bba8792485c0a4cc47cf66"`);
        await queryRunner.query(`ALTER TABLE "ai_results" DROP CONSTRAINT "FK_566b2de994f05c69ae470d9daf9"`);
        await queryRunner.query(`ALTER TABLE "ingestion_jobs" DROP CONSTRAINT "FK_ba1faf3bce0450f77f5fe1fbfa7"`);
        await queryRunner.query(`ALTER TABLE "inventory_ledger" DROP CONSTRAINT "FK_e80d1aa0ddd69622c182116f5cf"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a837fef7baa06a7d7d1b175a1f8"`);
        await queryRunner.query(`ALTER TABLE "image_assets" DROP CONSTRAINT "FK_ebae1924f6d1fd22aa4c8bc12fd"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_channel"`);
        await queryRunner.query(`CREATE INDEX "idx_order_channel" ON "orders" ("channel", "ordered_at") `);
        await queryRunner.query(`ALTER TABLE "listing_records" DROP COLUMN "shopifyProductId"`);
        await queryRunner.query(`ALTER TABLE "listing_records" DROP COLUMN "ebayListingId"`);
        await queryRunner.query(`ALTER TABLE "listing_records" DROP COLUMN "publishedAt"`);
        await queryRunner.query(`ALTER TABLE "listing_records" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "listing_records" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "listing_records" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "listing_records" DROP COLUMN "version"`);
        await queryRunner.query(`ALTER TABLE "listing_records" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_actor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_entity"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "dashboard_metrics_cache"`);
        await queryRunner.query(`DROP INDEX "public"."idx_channel_listing_conn"`);
        await queryRunner.query(`DROP INDEX "public"."idx_channel_listing_listing"`);
        await queryRunner.query(`DROP INDEX "public"."idx_channel_listing_external"`);
        await queryRunner.query(`DROP TABLE "channel_listings"`);
        await queryRunner.query(`DROP INDEX "public"."idx_webhook_log_channel"`);
        await queryRunner.query(`DROP TABLE "channel_webhook_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sales_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sales_channel"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sales_listing"`);
        await queryRunner.query(`DROP TABLE "sales_records"`);
        await queryRunner.query(`DROP TABLE "fitment_years"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fitment_listing"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fitment_vehicle"`);
        await queryRunner.query(`DROP TABLE "part_fitments"`);
        await queryRunner.query(`DROP TABLE "fitment_engines"`);
        await queryRunner.query(`DROP TABLE "fitment_submodels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32713bba8792485c0a4cc47cf6"`);
        await queryRunner.query(`DROP TABLE "fitment_models"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a2d705447a819b8e30e77365b"`);
        await queryRunner.query(`DROP TABLE "fitment_makes"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_result_job"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ai_result_confidence"`);
        await queryRunner.query(`DROP TABLE "ai_results"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_review"`);
        await queryRunner.query(`DROP TABLE "ingestion_jobs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_listing"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_source"`);
        await queryRunner.query(`DROP TABLE "inventory_events"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ledger_low_stock"`);
        await queryRunner.query(`DROP TABLE "inventory_ledger"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_recipient"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_item_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_item_listing"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "pricing_rules"`);
        await queryRunner.query(`DROP TABLE "shipping_profiles"`);
        await queryRunner.query(`DROP TABLE "tenant_settings"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_channel"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_buyer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_external"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."idx_channel_conn_user"`);
        await queryRunner.query(`DROP TABLE "channel_connections"`);
        await queryRunner.query(`DROP INDEX "public"."idx_image_listing"`);
        await queryRunner.query(`DROP INDEX "public"."idx_image_s3"`);
        await queryRunner.query(`DROP INDEX "public"."idx_image_job"`);
        await queryRunner.query(`DROP TABLE "image_assets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c134b2b0165e2bf9e479e5bb03"`);
        await queryRunner.query(`DROP TABLE "listing_revisions"`);
    }

}
