/**
 * Common automotive OEM makes and aftermarket brands for the new-listing brand combobox.
 * Merged with distinct cBrand values from the catalog at runtime.
 */
export const AUTOMOTIVE_OEM_BRANDS: readonly string[] = [
  'ACDelco',
  'Acura',
  'Alfa Romeo',
  'Audi',
  'BMW',
  'Bosch',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Continental',
  'Delphi',
  'Denso',
  'Dodge',
  'Fiat',
  'Ford',
  'Genuine OEM',
  'GMC',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jaguar',
  'Jeep',
  'Kia',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Mazda',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Mopar',
  'Motorcraft',
  'Nissan',
  'Porsche',
  'Ram',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Valeo',
  'Volkswagen',
  'Volvo',
] as const;

export const SKU_PREFIX = 'BLA';
