#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import dotenv from 'dotenv';
import pg from 'pg';
dotenv.config({path:'/app/.env'});
const {Pool}=pg;
const INPUT='/app/output/ebay-pipeline/napa_ebay_shopify_listings.seo-enriched.csv';
const CAND='/app/output/ebay-pipeline/napa_fitment_ai_candidates.json';
const OUT='/app/output/ebay-pipeline/napa_ebay_shopify_listings.fitment-enriched.csv';
const READY='/app/output/ebay-pipeline/napa_ebay_shopify_listings.fitment-enriched.ebay-listings-ready.csv';
const MANIFEST='/app/output/ebay-pipeline/napa_ebay_shopify_listings.fitment.manifest.json';
function parseCsv(text){const rows=[];let row=[],cell='',q=false;const s=text.replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const ch=s[i];if(q){if(ch==='"'&&s[i+1]==='"'){cell+='"';i++}else if(ch==='"')q=false;else cell+=ch}else if(ch==='"')q=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}if(cell.length||row.length){row.push(cell);rows.push(row)}return rows.filter(r=>r.some(v=>String(v).trim()));}
function cell(v){const s=v==null?'':String(v);return /[",\r\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s}
function csv(rows,headers){return [headers,...rows].map(r=>headers.map((h,i)=>cell(Array.isArray(r)?r[i]:r[h])).join(',')).join('\n')+'\n'}
function norm(h){return String(h||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function properBrand(s){const u=String(s||'').trim().toUpperCase();return ({NAPA:'NAPA',SKF:'SKF',MEVOTECH:'Mevotech',DELPHI:'Delphi'}[u]||String(s||'').trim())}
function titleCase(s){return String(s||'').toLowerCase().replace(/\b[a-z]/g,c=>c.toUpperCase())}
function clean(s){return String(s||'').replace(/[^A-Za-z0-9\s&+./-]/g,' ').replace(/\s+/g,' ').trim()}
function val(raw,...names){for(const n of names){const k=Object.keys(raw).find(x=>norm(x)===norm(n));if(k&&String(raw[k]??'').trim())return String(raw[k]).trim()}return ''}
function key(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function yearNum(v){const n=Number(v);return Number.isFinite(n)&&n>=1900&&n<=2100?Math.trunc(n):0}
function shortenMake(m){return ({Chevrolet:'Chevy','Mercedes-Benz':'Mercedes',Volkswagen:'VW'}[m]||m)}
function compactFitment(f){return {make:f.make,model:f.model,yearStart:f.yearStart,yearEnd:f.yearEnd,generation:f.generation||'',position:f.position||'',confidence:Number(f.confidence)||0,basis:f.basis||'',source:'GPT-5.6 Luna + eBay US MVL 2026-05'}}
function buildTitle(row,fit){const brand=properBrand(row.brand),mpn=row.mpn,part=titleCase(row.partType||'Automotive Part');const pos=(fit[0]?.position||'').trim();const base=[brand,mpn,part,pos].filter(Boolean).join(' ');const vehicles=[];for(const f of fit){const gen=String(f.generation||'').replace(/generation|first|second|third|fourth|fifth/ig,'').replace(/[()]/g,'').replace(/\s+/g,' ').trim();const v=[shortenMake(f.make),f.model,gen].filter(Boolean).join(' ');if(!vehicles.includes(v))vehicles.push(v)}let t=clean(base+' for '+vehicles.slice(0,2).join(' '));if(t.length<=80)return t; t=clean(base+' for '+vehicles[0]);if(t.length<=80)return t; t=clean([brand,mpn,part,pos,'for',vehicles[0]].filter(Boolean).join(' '));if(t.length<=80)return t;return clean([brand,mpn,part,'for',vehicles[0]].filter(Boolean).join(' ')).slice(0,80).trim()}
function details(f,y){const a=['Year='+y,'Make='+f.make,'Model='+f.model];if(f.submodel)a.push('Submodel='+f.submodel);if(f.trim)a.push('Trim='+f.trim);if(f.engine)a.push('Engine='+f.engine);return a.join('|')}
async function main(){const p=parseCsv(fs.readFileSync(INPUT,'utf8'));const headers=p.shift();const source=p.map((r,i)=>({sourceIndex:i,cells:r,raw:Object.fromEntries(headers.map((h,j)=>[h,r[j]??'']))}));const cand=JSON.parse(fs.readFileSync(CAND,'utf8'));const citems=cand.items||{};const pool=new Pool({host:process.env.DB_HOST,port:Number(process.env.DB_PORT),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,max:4});const client=await pool.connect();const cache=new Map();async function validate(f){const make=String(f.make||'').trim(),model=String(f.model||'').trim(),ys=yearNum(f.yearStart),ye=yearNum(f.yearEnd)||ys;if(!make||!model||!ys)return null;const ck=make+'|'+model+'|'+ys+'|'+ye;if(cache.has(ck))return cache.get(ck);let r=await client.query('select make,model,min(year)::int as ymin,max(year)::int as ymax,count(*)::int as n from ebay_mvl_entries where marketplace=\'US\' and lower(make)=lower($1) and year between $3 and $4 and (lower(model)=lower($2) or lower(model) like lower($2)||\'%\' or lower($2) like lower(model)||\'%\') group by make,model',[make,model,ys,ye]);if(!r.rows.length)r=await client.query('select make,model,min(year)::int as ymin,max(year)::int as ymax,count(*)::int as n from ebay_mvl_entries where marketplace=\'US\' and lower(make)=lower($1) and year between $3 and $4 group by make,model having regexp_replace(lower(model),\'[^a-z0-9]\',\'\',\'g\')=regexp_replace(lower($2),\'[^a-z0-9]\',\'\',\'g\')',[make,model,ys,ye]);if(!r.rows.length){cache.set(ck,null);return null}const best=r.rows.sort((a,b)=>b.n-a.n)[0];const out={...f,make:best.make,model:best.model,yearStart:Math.max(ys,Number(best.ymin)),yearEnd:Math.min(ye,Number(best.ymax)),mvlRows:Number(best.n)};cache.set(ck,out);return out}
const enriched=[];let acceptedRows=0,rejectedRows=0,fitRows=0,sourceWithCandidates=0;for(const s of source){const raw=s.raw;const item=citems[String(s.sourceIndex)]||{};const fs0=Array.isArray(item.fitments)?item.fitments:[];if(fs0.length)sourceWithCandidates++;const valid=[];for(const f of fs0){if((Number(f.confidence)||0)<0.70)continue;const v=await validate(f);if(v)valid.push(compactFitment(v));}const unique=[];const seen=new Set();for(const f of valid){const k=f.make+'|'+f.model+'|'+f.yearStart+'|'+f.yearEnd;if(!seen.has(k)){seen.add(k);unique.push(f)}}if(unique.length)acceptedRows++;else if(fs0.length)rejectedRows++;fitRows+=unique.length;const row={...raw};const title=unique.length?buildTitle({brand:val(raw,'Brand'),mpn:val(raw,'MPN'),partType:val(raw,'Product Type','Part Type')},unique):val(raw,'SEO Title','Title');const desc=val(raw,'SEO Description','Description');const fitText=unique.length?' Verified vehicle applications: '+unique.map(f=>f.yearStart===f.yearEnd?f.yearStart:(f.yearStart+'-'+f.yearEnd)+' '+f.make+' '+f.model).join('; ')+'.': ' Fitment remains pending because no candidate passed eBay MVL validation.';const set=(names,v)=>{const h=Object.keys(row).find(x=>names.map(norm).includes(norm(x)));if(h)row[h]=v};set(['SEO Title'],title);set(['Title'],title);set(['SEO Description'],(desc+fitText).trim());row['Fitment Data']=JSON.stringify(unique);row['Fitment Source']=unique.length?'GPT-5.6 Luna + eBay US MVL 2026-05':'';row['Fitment Confidence']=unique.length?Math.min(...unique.map(f=>f.confidence)).toFixed(2):'';row['Fitment Status']=unique.length?'verified_mvl':'fitment_pending';row['Title Status']=unique.length?'completed_vehicle_enriched':(val(raw,'Title Status')||'completed');const hasImage=Boolean(val(raw,'Image URL'));row['Publish Status']=hasImage&&unique.length?'content_ready_fitment_verified':(hasImage?'blocked_fitment_pending':'blocked_missing_image');row['Review Reason']=hasImage&&unique.length?'Fitment and image validated for staged export':(hasImage?'Fitment evidence did not pass MVL validation':'No validated image and/or fitment evidence');enriched.push(row)}
const outHeaders=[...headers,...['Fitment Data','Fitment Source','Fitment Confidence','Fitment Status']].filter((h,i,a)=>a.indexOf(h)===i);const outRows=enriched.map(r=>outHeaders.map(h=>r[h]??''));fs.writeFileSync(OUT,csv(outRows,outHeaders));
const readyHeaders=['*Action','CustomLabel (SKU)','*Title','*Quantity','*ConditionID','*Category','*Description','PicURL','C:Brand','C:Type','C:Manufacturer Part Number','C:OE/OEM Part Number','P:UPC','P:EAN','Pipeline Import ID','Publish Status','Relationship','Relationship details','Fitment Source','Fitment Confidence'];const ready=[];for(const r of enriched){const sku=val(r,'Custom Label (SKU)','SKU'),fit=(()=>{try{return JSON.parse(r['Fitment Data']||'[]')}catch{return[]}})(),qty=val(r,'Quantity'),cond=val(r,'Condition'),cat=val(r,'Category'),desc=val(r,'SEO Description','Description'),img=val(r,'Image URL'),brand=properBrand(val(r,'Brand')),type=titleCase(val(r,'Product Type','Part Type')),mpn=val(r,'MPN'),inter=val(r,'Interchange Part Number'),upc=val(r,'UPC'),ean=val(r,'EAN'),status=r['Publish Status']||'';ready.push(['Add',sku,val(r,'SEO Title','Title'),qty,cond.toLowerCase()==='new'?'1000':'',cat,desc,img,brand,type,mpn,inter,upc,ean,'31fe3770-48c8-4667-9351-af4a1fad99ad',status,'','',r['Fitment Source']||'',r['Fitment Confidence']||'']);for(const f of fit){for(let y=f.yearStart;y<=f.yearEnd;y++)ready.push(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Compatibility',details(f,y),r['Fitment Source']||'',r['Fitment Confidence']||''])}}fs.writeFileSync(READY,csv(ready,readyHeaders));
try{await client.query('begin');for(const r of enriched){const sku=val(r,'Custom Label (SKU)','SKU'),upc=val(r,'UPC'),fit=(()=>{try{return JSON.parse(r['Fitment Data']||'[]')}catch{return[]}})(),status=r['Fitment Status'],conf=fit.length?Math.min(...fit.map(f=>Number(f.confidence)||0)):null;if(!sku&&!upc)continue;await client.query('update catalog_products set fitment_data=$1::jsonb, fitment_rows=$1::jsonb, fitment_status=$2, fitment_confidence=$3, "updatedAt"=now() where lower(coalesce(sku,\'\'))=lower($4) or (coalesce(upc,\'\')<>\'\' and upc=$5)',[JSON.stringify(fit),status,conf,sku,upc])}await client.query('commit')}catch(e){await client.query('rollback');console.error('db update failed',e.message)}finally{client.release();await pool.end()}
const manifest={model:'gpt-5.6-luna',sourceRows:source.length,sourceBrands:[...new Set(source.map(s=>val(s.raw,'Brand')).filter(Boolean))],aiCandidateRows:sourceWithCandidates,mvlValidatedRows:acceptedRows,mvlRejectedCandidateRows:rejectedRows,fitmentRows:fitRows,titleVehicleEnrichedRows:acceptedRows,imageRows:enriched.filter(r=>Boolean(val(r,'Image URL'))).length,missingImageRows:enriched.filter(r=>!Boolean(val(r,'Image URL'))).length,publishReadyRows:enriched.filter(r=>r['Publish Status']==='content_ready_fitment_verified').length,liveEbayPublishPerformed:false,output:OUT,readyOutput:READY};fs.writeFileSync(MANIFEST,JSON.stringify(manifest,null,2));console.log(JSON.stringify(manifest,null,2))}
main().catch(e=>{console.error(e);process.exitCode=1})